env:
  browser: true
  es2021: true
  node: true
extends:
- "plugin:functional/recommended"
- "plugin:functional/external-recommended"
- "plugin:functional/stylistic"
plugins: [ "functional" ]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  semi:
  - warn
  - never
  quotes:
  - warn
  - double
  comma-style: 
  - warn
  - first
  comma-spacing:
  - warn
  - before: false
    after: true
